jobs:
  build:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run: cargo --version
      - run: cargo build --features reqwest
      - run: cargo build --features spin --target wasm32-wasi
      - run: cargo install espup
      - run: cargo espup install